/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_FoodSystem;


import hms_ETC.BillCard;
import hms_ETC.BillCash;
import hms_Reservation.hotelGUI;
import javax.swing.JOptionPane;

/**
 *
 * @author 송진영
 */
public class foodtrace extends hmsDB_FoodSystem {
     
    /**
     * Creates new form foodtrace
     */
    int choice = 0;
    public foodtrace() {
        initComponents();
         dbLoad();
        Menu1Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+1));
            Menu2Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+2));
            Menu3Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+3));
            Menu4Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+4));
            Menu5Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+5));
            Menu6Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_"+6));
            if(this.getfoodString("hmsfood", "foodtype", "1", "food_1").isEmpty()) Menu1ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_1").isEmpty()) Menu1ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_2").isEmpty()) Menu2ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_2").isEmpty()) Menu1ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_3").isEmpty()) Menu3ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_3").isEmpty()) Menu1ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_4").isEmpty()) Menu4ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_4").isEmpty()) Menu4ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_5").isEmpty()) Menu5ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_5").isEmpty()) Menu5ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_6").isEmpty()) Menu6ChargeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_6").isEmpty()) Menu6ChargeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_1").isEmpty()) Menu1ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_1").isEmpty()) Menu1ConsumeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_2").isEmpty()) Menu2ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_2").isEmpty()) Menu2ConsumeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_3").isEmpty()) Menu3ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_3").isEmpty()) Menu3ConsumeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_4").isEmpty()) Menu4ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_4").isEmpty()) Menu4ConsumeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_5").isEmpty()) Menu5ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_5").isEmpty()) Menu5ConsumeField.setEnabled(true);
            if(getfoodString("hmsfood", "foodtype", "1", "food_6").isEmpty()) Menu6ConsumeField.setEnabled(false);
            else if(!getfoodString("hmsfood", "foodtype", "1", "food_6").isEmpty()) Menu6ConsumeField.setEnabled(true);
            

            
            buttonGroup1.add(CardRadio);
            buttonGroup1.add(CashRadio);
            dbClose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        minibarLabel = new javax.swing.JLabel();
        Menu1ChargeField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        Menu2ChargeField = new javax.swing.JTextField();
        ChargeButton = new javax.swing.JButton();
        ConsumeButton = new javax.swing.JButton();
        Menu3ChargeField = new javax.swing.JTextField();
        Menu4ChargeField = new javax.swing.JTextField();
        Menu5ChargeField = new javax.swing.JTextField();
        Menu6ChargeField = new javax.swing.JTextField();
        RoomNumField = new javax.swing.JTextField();
        RoomLabel = new javax.swing.JLabel();
        BillScrollPane = new javax.swing.JScrollPane();
        BillTextArea = new javax.swing.JTextArea();
        BillLabel = new javax.swing.JLabel();
        PayButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        Menu1Field = new javax.swing.JLabel();
        Menu2Field = new javax.swing.JLabel();
        Menu3Field = new javax.swing.JLabel();
        Menu4Field = new javax.swing.JLabel();
        Menu5Field = new javax.swing.JLabel();
        Menu6Field = new javax.swing.JLabel();
        Menu1ConsumeField = new javax.swing.JTextField();
        Menu2ConsumeField = new javax.swing.JTextField();
        Menu3ConsumeField = new javax.swing.JTextField();
        Menu4ConsumeField = new javax.swing.JTextField();
        Menu5ConsumeField = new javax.swing.JTextField();
        Menu6ConsumeField = new javax.swing.JTextField();
        CardRadio = new javax.swing.JRadioButton();
        CashRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("식품 추적");

        minibarLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        minibarLabel.setText("미니바");

        Menu1ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu1ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ChargeFieldActionPerformed(evt);
            }
        });

        SearchButton.setBackground(new java.awt.Color(113, 113, 113));
        SearchButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("조회");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        Menu2ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu2ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ChargeFieldActionPerformed(evt);
            }
        });

        ChargeButton.setBackground(new java.awt.Color(113, 113, 113));
        ChargeButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ChargeButton.setForeground(new java.awt.Color(255, 255, 255));
        ChargeButton.setText("충전");
        ChargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeButtonActionPerformed(evt);
            }
        });

        ConsumeButton.setBackground(new java.awt.Color(113, 113, 113));
        ConsumeButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ConsumeButton.setForeground(new java.awt.Color(255, 255, 255));
        ConsumeButton.setText("소비");
        ConsumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsumeButtonActionPerformed(evt);
            }
        });

        Menu3ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu3ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu3ChargeFieldActionPerformed(evt);
            }
        });

        Menu4ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu4ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu4ChargeFieldActionPerformed(evt);
            }
        });

        Menu5ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu5ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu5ChargeFieldActionPerformed(evt);
            }
        });

        Menu6ChargeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu6ChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu6ChargeFieldActionPerformed(evt);
            }
        });

        RoomNumField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumFieldActionPerformed(evt);
            }
        });

        RoomLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomLabel.setText("방번호");

        BillTextArea.setColumns(20);
        BillTextArea.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        BillTextArea.setRows(5);
        BillScrollPane.setViewportView(BillTextArea);

        BillLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        BillLabel.setText("청구서");

        PayButton.setBackground(new java.awt.Color(113, 113, 113));
        PayButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        PayButton.setForeground(new java.awt.Color(255, 255, 255));
        PayButton.setText("결제");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        GoBackButton.setBackground(new java.awt.Color(70, 70, 70));
        GoBackButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GoBackButton.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton.setText("뒤로가기");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        Menu1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu1Field.setText(" ");

        Menu2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu2Field.setText(" ");

        Menu3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu3Field.setText(" ");

        Menu4Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu4Field.setText(" ");

        Menu5Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu5Field.setText(" ");

        Menu6Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu6Field.setText(" ");

        Menu1ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu1ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ConsumeFieldActionPerformed(evt);
            }
        });

        Menu2ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu2ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ConsumeFieldActionPerformed(evt);
            }
        });

        Menu3ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu3ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu3ConsumeFieldActionPerformed(evt);
            }
        });

        Menu4ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu4ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu4ConsumeFieldActionPerformed(evt);
            }
        });

        Menu5ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu5ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu5ConsumeFieldActionPerformed(evt);
            }
        });

        Menu6ConsumeField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        Menu6ConsumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu6ConsumeFieldActionPerformed(evt);
            }
        });

        CardRadio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        CardRadio.setText("카드");
        CardRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardRadioActionPerformed(evt);
            }
        });

        CashRadio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        CashRadio.setText("현금");
        CashRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(RoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Menu1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(Menu2Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu3Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu5Field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu4Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu6Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Menu3ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu4ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu2ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu1ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu5ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu6ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Menu3ConsumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(Menu4ConsumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(Menu5ConsumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(Menu6ConsumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(Menu2ConsumeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Menu1ConsumeField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ChargeButton)
                            .addGap(70, 70, 70)
                            .addComponent(ConsumeButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(minibarLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SearchButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BillScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CardRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CashRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GoBackButton)))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minibarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(RoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomLabel)
                    .addComponent(PayButton)
                    .addComponent(GoBackButton)
                    .addComponent(CardRadio)
                    .addComponent(CashRadio))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Menu1Field)
                            .addComponent(Menu1ConsumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu1ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Menu2Field)
                                    .addComponent(Menu2ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Menu3Field)
                                    .addComponent(Menu3ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Menu2ConsumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Menu3ConsumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Menu4ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu4Field)
                            .addComponent(Menu4ConsumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Menu5ConsumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu5ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Menu5Field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Menu6ChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Menu6Field))
                            .addComponent(Menu6ConsumeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsumeButton)
                            .addComponent(ChargeButton))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BillScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ChargeFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Menu1ChargeFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        
        String[] mealname = new String[6];
        String[] mealname2 = new String[3];
        String[] mealname3 = new String[3];
        int[] mealnum = new int[6];
        int[] mealnum2 = new int[3];
        int[] mealnum3 = new int[3];
        String result = "";
        int resultpay = 0;
        String c = RoomNumField.getText();
        if(search_roomnum(c) != null)  
        {
        for(int i=0; i<6; i++)
        {
            mealname[i] = getfoodString("hmsfood", "foodtype", "1", "food_"+(i+1));
            mealnum[i] = getfoodint("foodsystem", "room_num", c, "food_"+(i+1)+"_num");
            if(!getfoodString("hmsfood", "foodtype", "1", "food_"+(i+1)).isEmpty())
            {
                int charge = getfoodint("foodsystem", "room_num", c, "food_"+(i+1)+"_charge");
                int pay = getfoodint("hmsfood", "foodtype", "1", "food_"+(i+1)+"_pay");
                result += mealname[i] + " " + charge + "개\n";
                resultpay += charge * pay;
            }
        }
        for(int i=0; i<3; i++)
        {
            mealname2[i] = getfoodString("hmsfood", "foodtype", "2", "food_"+(i+1));
            mealnum2[i] = getfoodint("foodsystem", "room_num", c, "food_service_"+(i+1));
            if(!getfoodString("hmsfood", "foodtype", "2", "food_"+(i+1)).isEmpty())
            {
                result += mealname2[i] + " 코스 " + mealnum2[i] + "개\n";
                resultpay += mealnum2[i] * getfoodint("hmsfood", "foodtype", "2", "food_"+(i+1)+"_pay");
            }
        }
        for(int i=0; i<3; i++)
        {
            mealname3[i] = getfoodString("hmsfood", "foodtype", "3", "food_"+(i+1));
            mealnum3[i] = getfoodint("foodsystem", "room_num", c, "food_service_"+(i+3));
            if(!getfoodString("hmsfood", "foodtype", "3", "food_"+(i+1)).isEmpty())
            {
                result += mealname3[i] + " 코스 " + mealnum3[i] + "개\n";
                resultpay += mealnum3[i] * getfoodint("hmsfood", "foodtype", "3", "food_"+(i+1)+"_pay");
            }
        }
        Updatechange("foodsystem", "food_total_pay", "room_num", RoomNumField.getText(), resultpay);
        result += "총액: "+ getfoodint("foodsystem", "room_num", RoomNumField.getText(), "food_total_pay");
            if(!mealname[0].isEmpty()) Menu1Field.setText(mealname[0] + "(" + mealnum[0]+")");
            if(!mealname[1].isEmpty()) Menu2Field.setText(mealname[1]+ "(" + mealnum[1]+")");
            if(!mealname[2].isEmpty()) Menu3Field.setText(mealname[2]+ "(" + mealnum[2]+")");
            if(!mealname[3].isEmpty()) Menu4Field.setText(mealname[3]+ "(" + mealnum[3]+")");
            if(!mealname[4].isEmpty()) Menu5Field.setText(mealname[4]+ "(" + mealnum[4]+")");
            if(!mealname[5].isEmpty()) Menu6Field.setText(mealname[5]+ "(" + mealnum[5]+")");
            BillTextArea.setText(result);
        }
        else JOptionPane.showMessageDialog(this, "일치하는 방번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        dbClose();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Menu2ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu2ChargeFieldActionPerformed

    private void Menu3ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu3ChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu3ChargeFieldActionPerformed

    private void ChargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        if(!search_roomnum(RoomNumField.getText()).isEmpty()){
            
            
            
            if((Menu1ChargeField.getText().equals("") == false)) 
            Updateint("foodsystem", "food_1_num", "room_num", RoomNumField.
            getText(), Integer.parseInt(Menu1ChargeField.getText()));
            if((Menu2ChargeField.getText().equals("") == false) && !getfoodString
            ("hmsfood", "foodtype", "1", "food_2").isEmpty())
            Updateint("foodsystem", "food_2_num", "room_num", RoomNumField.getText(),
            Integer.parseInt(Menu2ChargeField.getText()));
        
        
        
        
        if((Menu3ChargeField.getText().equals("") == false) && !getfoodString("hmsfood", "foodtype", "1", "food_3").isEmpty())
            Updateint("foodsystem", "food_3_num", "room_num", RoomNumField.getText(), Integer.parseInt(Menu3ChargeField.getText()));
        if((Menu4ChargeField.getText().equals("") == false) && !getfoodString("hmsfood", "foodtype", "1", "food_4").isEmpty()) 
            Updateint("foodsystem", "food_4_num", "room_num", RoomNumField.getText(), Integer.parseInt(Menu4ChargeField.getText()));
        if((Menu5ChargeField.getText().equals("") == false) && !getfoodString("hmsfood", "foodtype", "1", "food_5").isEmpty())
            Updateint("foodsystem", "food_5_num", "room_num", RoomNumField.getText(), Integer.parseInt(Menu5ChargeField.getText()));
        if((Menu6ChargeField.getText().equals("") == false) && !getfoodString("hmsfood", "foodtype", "1", "food_6").isEmpty()) 
            Updateint("foodsystem", "food_6_num", "room_num", RoomNumField.getText(), Integer.parseInt(Menu6ChargeField.getText()));
        if(Menu1ChargeField.getText().equals("") == false || Menu2ChargeField.getText().equals("") == false || Menu3ChargeField.getText().equals("") == false || Menu4ChargeField.getText().equals("") == false ||
                Menu5ChargeField.getText().equals("") == false || Menu6ChargeField.getText().equals("") == false) JOptionPane.showMessageDialog(this, "음식이 충전되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this, "충전할 수량을 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "일치하는 방번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        
        Menu1ChargeField.setText(null);
        Menu2ChargeField.setText(null);
        Menu3ChargeField.setText(null);
        Menu4ChargeField.setText(null);
        Menu5ChargeField.setText(null);
        Menu6ChargeField.setText(null);
        
        SearchButtonActionPerformed(evt);        
        dbClose();
    }//GEN-LAST:event_ChargeButtonActionPerformed

    private void ConsumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumeButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        String room = RoomNumField.getText();
        int count = 0;
        int[] meal = new int[6];
        for(int i=0; i<6; i++)
        {
            meal[i] = getfoodint("foodsystem", "room_num", room, "food_"+(i+1)+"_num");
        }
        if(search_roomnum(room) != null){
            if((Menu1ConsumeField.getText().equals("") == false) && meal[0] >= Integer.parseInt(Menu1ConsumeField.getText())) {
                Updateint("foodsystem", "food_1_charge", "room_num", room, Integer.parseInt(Menu1ConsumeField.getText()));
                Updateint("foodsystem", "food_1_record", "room_num", room, Integer.parseInt(Menu1ConsumeField.getText()));
                Updateint("foodsystem", "food_1_num", "room_num", room, -Integer.parseInt(Menu1ConsumeField.getText()));
                count++;
            }
        if((Menu2ConsumeField.getText().equals("") == false) && meal[1] >= Integer.parseInt(Menu2ConsumeField.getText())) 
        {
            Updateint("foodsystem", "food_2_charge", "room_num", room, Integer.parseInt(Menu2ConsumeField.getText()));
            Updateint("foodsystem", "food_2_record", "room_num", room, Integer.parseInt(Menu2ConsumeField.getText()));
            Updateint("foodsystem", "food_2_num", "room_num", room, -Integer.parseInt(Menu2ConsumeField.getText()));
            count++;
        }
        if((Menu3ConsumeField.getText().equals("") == false) && meal[2] >= Integer.parseInt(Menu3ConsumeField.getText())) 
        {
            Updateint("foodsystem", "food_3_charge", "room_num", room, Integer.parseInt(Menu3ConsumeField.getText()));
            Updateint("foodsystem", "food_3_record", "room_num", room, Integer.parseInt(Menu3ConsumeField.getText()));
            Updateint("foodsystem", "food_3_num", "room_num", room, -Integer.parseInt(Menu3ConsumeField.getText()));
            count++;
        }
        if((Menu4ConsumeField.getText().equals("") == false) && meal[3] >= Integer.parseInt(Menu4ConsumeField.getText()))
        {
            Updateint("foodsystem", "food_4_charge", "room_num", room, Integer.parseInt(Menu4ConsumeField.getText()));
            Updateint("foodsystem", "food_4_record", "room_num", room, Integer.parseInt(Menu4ConsumeField.getText()));
            Updateint("foodsystem", "food_4_num", "room_num", room, -Integer.parseInt(Menu4ConsumeField.getText()));
            count++;
        }
        if((Menu5ConsumeField.getText().equals("") == false) && meal[4] >= Integer.parseInt(Menu5ConsumeField.getText()))
        {
            Updateint("foodsystem", "food_5_charge", "room_num", room, Integer.parseInt(Menu5ConsumeField.getText()));
            Updateint("foodsystem", "food_5_record", "room_num", room, Integer.parseInt(Menu5ConsumeField.getText()));
            Updateint("foodsystem", "food_5_num", "room_num", room, -Integer.parseInt(Menu5ConsumeField.getText()));
            count++;
        }
        
        if((Menu6ConsumeField.getText().equals("") == false) && meal[5] >= Integer.parseInt(Menu6ConsumeField.getText()))
        {
            Updateint("foodsystem", "food_6_charge", "room_num", room, Integer.parseInt(Menu6ConsumeField.getText()));
            Updateint("foodsystem", "food_6_record", "room_num", room, Integer.parseInt(Menu6ConsumeField.getText()));
            Updateint("foodsystem", "food_6_num", "room_num", room, -Integer.parseInt(Menu6ConsumeField.getText()));
            count++;
        }

        if(count == 0)
        {
            JOptionPane.showMessageDialog(this, "음식 수량보다 소비 수량이 많습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Menu1ConsumeField.getText().equals("") == false || Menu2ConsumeField.getText().equals("") == false || Menu3ConsumeField.getText().equals("") == false || Menu4ConsumeField.getText().equals("") == false ||
                Menu5ConsumeField.getText().equals("") == false || Menu6ConsumeField.getText().equals("") == false) JOptionPane.showMessageDialog(this, "음식 소비량이 추가되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this, "소비 수량을 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);

        
        }
        
        else{
            JOptionPane.showMessageDialog(this, "일치하는 방번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        Menu1ConsumeField.setText(null);
        Menu2ConsumeField.setText(null);
        Menu3ConsumeField.setText(null);
        Menu4ConsumeField.setText(null);
        Menu5ConsumeField.setText(null);
        Menu6ConsumeField.setText(null);
        SearchButtonActionPerformed(evt);
        dbClose();
    }//GEN-LAST:event_ConsumeButtonActionPerformed

    private void Menu6ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu6ChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu6ChargeFieldActionPerformed

    private void RoomNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNumFieldActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        String room_num = RoomNumField.getText();
        
        dbLoad();
        String card_num = Card_num(room_num);
        int pay = getfoodint("foodsystem", "room_num", room_num, "food_total_pay");
        
        if(!room_num.isEmpty() && search_roomnum_2(room_num,"reservation")!=null)
        {
            if(pay != 0)
          {
            if(choice == 0) JOptionPane.showMessageDialog(this, "결제수단을 선택해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
            else if(choice== 1)
            {
                dispose();
                new BillCard(card_num, room_num, 2).setVisible(true);
            }
            else if(choice == 2)
            {
                dispose();
                new BillCash(room_num, 2).setVisible(true);
            }
            
         }
        else JOptionPane.showMessageDialog(this, "결제할 금액이 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(search_roomnum_2(room_num,"reservation") == null)
        {
            JOptionPane.showMessageDialog(this, "일치하는 방번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        else JOptionPane.showMessageDialog(this, "방번호를 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_PayButtonActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new hotelGUI().setVisible(true);
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void Menu4ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu4ChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu4ChargeFieldActionPerformed

    private void Menu5ChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu5ChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu5ChargeFieldActionPerformed

    private void Menu3ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu3ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu3ConsumeFieldActionPerformed

    private void Menu1ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1ConsumeFieldActionPerformed

    private void Menu2ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu2ConsumeFieldActionPerformed

    private void Menu4ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu4ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu4ConsumeFieldActionPerformed

    private void Menu5ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu5ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu5ConsumeFieldActionPerformed

    private void Menu6ConsumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu6ConsumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu6ConsumeFieldActionPerformed

    private void CardRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardRadioActionPerformed
        // TODO add your handling code here:
        choice = 1;
    }//GEN-LAST:event_CardRadioActionPerformed

    private void CashRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashRadioActionPerformed
        // TODO add your handling code here:
        choice = 2;
    }//GEN-LAST:event_CashRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BillLabel;
    private javax.swing.JScrollPane BillScrollPane;
    private javax.swing.JTextArea BillTextArea;
    private javax.swing.JRadioButton CardRadio;
    private javax.swing.JRadioButton CashRadio;
    private javax.swing.JButton ChargeButton;
    private javax.swing.JButton ConsumeButton;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JTextField Menu1ChargeField;
    private javax.swing.JTextField Menu1ConsumeField;
    private javax.swing.JLabel Menu1Field;
    private javax.swing.JTextField Menu2ChargeField;
    private javax.swing.JTextField Menu2ConsumeField;
    private javax.swing.JLabel Menu2Field;
    private javax.swing.JTextField Menu3ChargeField;
    private javax.swing.JTextField Menu3ConsumeField;
    private javax.swing.JLabel Menu3Field;
    private javax.swing.JTextField Menu4ChargeField;
    private javax.swing.JTextField Menu4ConsumeField;
    private javax.swing.JLabel Menu4Field;
    private javax.swing.JTextField Menu5ChargeField;
    private javax.swing.JTextField Menu5ConsumeField;
    private javax.swing.JLabel Menu5Field;
    private javax.swing.JTextField Menu6ChargeField;
    private javax.swing.JTextField Menu6ConsumeField;
    private javax.swing.JLabel Menu6Field;
    private javax.swing.JButton PayButton;
    private javax.swing.JLabel RoomLabel;
    private javax.swing.JTextField RoomNumField;
    private javax.swing.JButton SearchButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel minibarLabel;
    // End of variables declaration//GEN-END:variables
}
