/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_FoodSystem;

import javax.swing.JOptionPane;
import hms_Reservation.hotelGUI;

/**
 *
 * @author 송진영
 */
public class foodService extends hmsDB_FoodSystem {


    /**
     * Creates new form foodService
     */
static int choice;
static int choice2;
String room_num;
    public foodService() {
        
        initComponents();
        dbLoad();
        room_num = RoomNumField.getText();
        // 식당 메뉴
        ResCourse1Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_1")+" ("+getfoodint("hmsfood", "foodtype", "2", "food_1_pay") +"원)");
       ResCourse2Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_2")+" ("+getfoodint("hmsfood", "foodtype", "2", "food_2_pay") +"원)");
       ResCourse3Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_3")+" ("+getfoodint("hmsfood", "foodtype", "2", "food_3_pay") +"원)");
       // 룸서비스 메뉴
       RoomCourse1Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_1")+" ("+getfoodint("hmsfood", "foodtype", "3", "food_1_pay") +"원)");
       RoomCourse2Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_2")+" ("+getfoodint("hmsfood", "foodtype", "3", "food_2_pay") +"원)");
       RoomCourse3Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_3")+" ("+getfoodint("hmsfood", "foodtype", "3", "food_3_pay") +"원)");
       
       buttonGroup1.add(ResCourse1Radio);
       buttonGroup1.add(ResCourse2Radio);
       buttonGroup1.add(RoomCourse1Radio);
       buttonGroup1.add(RoomCourse2Radio);
       buttonGroup1.add(ResCourse3Radio);
       buttonGroup1.add(RoomCourse3Radio);
       dbClose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        RestaurantLabel = new javax.swing.JLabel();
        ReserButton = new javax.swing.JButton();
        RoomServiceLabel = new javax.swing.JLabel();
        RoomNumField = new javax.swing.JTextField();
        RoomnumLabel = new javax.swing.JLabel();
        ResCourse1Field = new javax.swing.JTextField();
        ResCourse2Field = new javax.swing.JTextField();
        ResCourse3Field = new javax.swing.JTextField();
        RoomCourse2Field = new javax.swing.JTextField();
        ResCourse1Radio = new javax.swing.JRadioButton();
        ResCourse2Radio = new javax.swing.JRadioButton();
        RoomCourse1Radio = new javax.swing.JRadioButton();
        RoomCourse2Radio = new javax.swing.JRadioButton();
        ResCourse3Radio = new javax.swing.JRadioButton();
        RoomCourse1Field = new javax.swing.JTextField();
        RoomCourse3Field = new javax.swing.JTextField();
        RoomCourse3Radio = new javax.swing.JRadioButton();
        GoBackButton = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("식당 및 룸서비스");

        RestaurantLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RestaurantLabel.setText("식당");

        ReserButton.setBackground(new java.awt.Color(113, 113, 113));
        ReserButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ReserButton.setForeground(new java.awt.Color(255, 255, 255));
        ReserButton.setText("예약");
        ReserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserButtonActionPerformed(evt);
            }
        });

        RoomServiceLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomServiceLabel.setText("룸서비스");

        RoomNumField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumFieldActionPerformed(evt);
            }
        });

        RoomnumLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomnumLabel.setText("방번호");

        ResCourse1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse1FieldActionPerformed(evt);
            }
        });

        ResCourse2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse2FieldActionPerformed(evt);
            }
        });

        ResCourse3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse3FieldActionPerformed(evt);
            }
        });

        RoomCourse2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse2FieldActionPerformed(evt);
            }
        });

        ResCourse1Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse1Radio.setText("A코스");
        ResCourse1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse1RadioActionPerformed(evt);
            }
        });

        ResCourse2Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse2Radio.setText("B코스");
        ResCourse2Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse2RadioActionPerformed(evt);
            }
        });

        RoomCourse1Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse1Radio.setText("A코스");
        RoomCourse1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse1RadioActionPerformed(evt);
            }
        });

        RoomCourse2Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse2Radio.setText("B코스");
        RoomCourse2Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse2RadioActionPerformed(evt);
            }
        });

        ResCourse3Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ResCourse3Radio.setText("C코스");
        ResCourse3Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResCourse3RadioActionPerformed(evt);
            }
        });

        RoomCourse1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse1FieldActionPerformed(evt);
            }
        });

        RoomCourse3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse3FieldActionPerformed(evt);
            }
        });

        RoomCourse3Radio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomCourse3Radio.setText("C코스");
        RoomCourse3Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomCourse3RadioActionPerformed(evt);
            }
        });

        GoBackButton.setBackground(new java.awt.Color(70, 70, 70));
        GoBackButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GoBackButton.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton.setText("뒤로가기");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RestaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResCourse1Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResCourse2Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResCourse3Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomCourse1Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomCourse2Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomCourse3Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RoomCourse3Field, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(RoomCourse1Field)
                            .addComponent(RoomCourse2Field, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(ResCourse3Field)
                            .addComponent(ResCourse2Field)
                            .addComponent(ResCourse1Field)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(RoomnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(RoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ReserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GoBackButton)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomnumLabel)
                    .addComponent(ReserButton)
                    .addComponent(GoBackButton))
                .addGap(26, 26, 26)
                .addComponent(RestaurantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResCourse1Radio)
                    .addComponent(ResCourse1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResCourse2Radio)
                    .addComponent(ResCourse2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResCourse3Radio)
                    .addComponent(ResCourse3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoomServiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomCourse1Radio)
                    .addComponent(RoomCourse1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomCourse2Radio)
                    .addComponent(RoomCourse2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomCourse3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomCourse3Radio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        String c = "";
        room_num = RoomNumField.getText();
        if(search_roomnum(room_num) != null)
        {
            
            if(choice == 0 && choice2 ==0) JOptionPane.showMessageDialog(this, "코스를 선택해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                for(int i=1; i<=3; i++)
            {
                
                if(choice != 0)
                {
                    if(!getfoodString("hmsfood", "foodtype", "2", "food_"+choice).isEmpty())
                    {
                        if(choice== 1)  c = "A코스";
                        else if(choice== 2) c = "B코스";
                        else if (choice== 3) c = "C코스";
                        Updateint("foodsystem", "food_"+(choice+6)+"_record", "room_num", room_num,1);
                        JOptionPane.showMessageDialog(this, "식당 "+c+"가 예약되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        new isRoomservice(room_num,choice).setVisible(true);
                        break;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "해당 코스가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                }
                else if(choice2 != 0)
                {
                    if(!getfoodString("hmsfood", "foodtype", "3", "food_"+choice2).isEmpty())
                    {
                        if(choice2== 1)  c = "A코스";
                        else if(choice2== 2) c = "B코스";
                        else if (choice2== 3) c = "C코스";
                        Updateint("foodsystem", "food_"+(choice2+9)+"_record", "room_num", room_num,1);
                        JOptionPane.showMessageDialog(this, "룸서비스 "+c+"가 예약되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                        new isRoomservice(room_num,choice2+3).setVisible(true);
                        break;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "해당 코스가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                }
                
                
            }
        }
        else
        {
             JOptionPane.showMessageDialog(this, "일치하는 방번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        dbClose();
        
    }//GEN-LAST:event_ReserButtonActionPerformed

    private void ResCourse2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResCourse2FieldActionPerformed

    private void ResCourse2RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse2RadioActionPerformed
        // TODO add your handling code here:
        choice2 = 0;
        choice= 2;
    }//GEN-LAST:event_ResCourse2RadioActionPerformed

    private void ResCourse1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse1RadioActionPerformed
        // TODO add your handling code here:
        choice2 = 0;
        choice= 1;
        
    }//GEN-LAST:event_ResCourse1RadioActionPerformed

    private void ResCourse1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse1FieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ResCourse1FieldActionPerformed

    private void RoomNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNumFieldActionPerformed

    private void RoomCourse1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse1RadioActionPerformed
        // TODO add your handling code here:

        choice= 0;
        choice2 = 1;
    }//GEN-LAST:event_RoomCourse1RadioActionPerformed

    private void RoomCourse2RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse2RadioActionPerformed
        // TODO add your handling code here:
        choice = 0;
        choice2= 2;
    }//GEN-LAST:event_RoomCourse2RadioActionPerformed

    private void RoomCourse1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomCourse1FieldActionPerformed

    private void ResCourse3RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse3RadioActionPerformed
        // TODO add your handling code here:

        choice= 3;
        choice2 = 0;
    }//GEN-LAST:event_ResCourse3RadioActionPerformed

    private void RoomCourse3RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse3RadioActionPerformed
        // TODO add your handling code here:
        choice = 0;
        choice2= 3;
    }//GEN-LAST:event_RoomCourse3RadioActionPerformed

    private void ResCourse3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResCourse3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResCourse3FieldActionPerformed

    private void RoomCourse2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomCourse2FieldActionPerformed

    private void RoomCourse3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomCourse3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomCourse3FieldActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new hotelGUI().setVisible(true);
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackButton;
    private javax.swing.JTextField ResCourse1Field;
    private javax.swing.JRadioButton ResCourse1Radio;
    private javax.swing.JTextField ResCourse2Field;
    private javax.swing.JRadioButton ResCourse2Radio;
    private javax.swing.JTextField ResCourse3Field;
    private javax.swing.JRadioButton ResCourse3Radio;
    private javax.swing.JButton ReserButton;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JTextField RoomCourse1Field;
    private javax.swing.JRadioButton RoomCourse1Radio;
    private javax.swing.JTextField RoomCourse2Field;
    private javax.swing.JRadioButton RoomCourse2Radio;
    private javax.swing.JTextField RoomCourse3Field;
    private javax.swing.JRadioButton RoomCourse3Radio;
    private javax.swing.JTextField RoomNumField;
    private javax.swing.JLabel RoomServiceLabel;
    private javax.swing.JLabel RoomnumLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
