/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_FoodSystem;

import hms_Main.hmsGUI;
import javax.swing.JOptionPane;

/**
 *
 * @author 송진영
 */
public class foodChange extends hmsDB_FoodSystem {

    /**
     * Creates new form foodChange
     */
    public foodChange() {
        initComponents();
        dbLoad();
        MinibarMenu1Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_1"));
        MinibarMenu2Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_2"));
        MinibarMenu3Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_3"));
        MinibarMenu4Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_4"));
        MinibarMenu5Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_5"));
        MinibarMenu6Field.setText(getfoodString("hmsfood", "foodtype", "1", "food_6"));
        
        MinibarPrice1Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_1_pay")));
        MinibarPrice2Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_2_pay")));
        MinibarPrice3Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_3_pay")));
        MinibarPrice4Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_4_pay")));
        MinibarPrice5Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_5_pay")));
        MinibarPrice6Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "1", "food_6_pay")));
        
        RestaurantMenu1Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_1"));
        RestaurantMenu2Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_2"));
        RestaurantMenu3Field.setText(getfoodString("hmsfood", "foodtype", "2", "food_3"));
        
        RestaurantPrice1Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "2", "food_1_pay")));
        RestaurantPrice2Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "2", "food_2_pay")));
        RestaurantPrice3Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "2", "food_3_pay")));
        
        RoomServiceMenu1Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_1"));
        RoomServiceMenu2Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_2"));
        RoomServiceMenu3Field.setText(getfoodString("hmsfood", "foodtype", "3", "food_3"));
        
        RoomServicePrice1Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "3", "food_1_pay")));
        RoomServicePrice2Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "3", "food_2_pay")));
        RoomServicePrice3Field.setText(Integer.toString(getfoodint("hmsfood", "foodtype", "3", "food_3_pay")));
        dbClose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateButton = new javax.swing.JButton();
        MinibarMenu1Field = new javax.swing.JTextField();
        MinibarMenu2Field = new javax.swing.JTextField();
        MinibarMenu3Field = new javax.swing.JTextField();
        MinibarMenuLabel = new javax.swing.JLabel();
        MinibarPriceLabel = new javax.swing.JLabel();
        MinibarMenu4Field = new javax.swing.JTextField();
        MinibarMenu5Field = new javax.swing.JTextField();
        MinibarMenu6Field = new javax.swing.JTextField();
        MinibarPrice1Field = new javax.swing.JTextField();
        MinibarPrice2Field = new javax.swing.JTextField();
        MinibarPrice3Field = new javax.swing.JTextField();
        MinibarPrice4Field = new javax.swing.JTextField();
        MinibarPrice5Field = new javax.swing.JTextField();
        MinibarPrice6Field = new javax.swing.JTextField();
        RestaurantMenu1Field = new javax.swing.JTextField();
        RestaurantMenu2Field = new javax.swing.JTextField();
        RestaurantMenu3Field = new javax.swing.JTextField();
        RestaurantPrice1Field = new javax.swing.JTextField();
        RestaurantPrice2Field = new javax.swing.JTextField();
        RestaurantPrice3Field = new javax.swing.JTextField();
        RoomServiceMenu1Field = new javax.swing.JTextField();
        RoomServiceMenu2Field = new javax.swing.JTextField();
        RoomServiceMenu3Field = new javax.swing.JTextField();
        RoomServicePrice1Field = new javax.swing.JTextField();
        RoomServicePrice2Field = new javax.swing.JTextField();
        RoomServicePrice3Field = new javax.swing.JTextField();
        RestaurantMenu = new javax.swing.JLabel();
        RestaurantPrice = new javax.swing.JLabel();
        RoomServiceMenuLabel = new javax.swing.JLabel();
        RoomServicePriceLabel = new javax.swing.JLabel();
        MinibarLabel = new javax.swing.JLabel();
        RestaurantLabel = new javax.swing.JLabel();
        RoomServiceLabel = new javax.swing.JLabel();
        GoBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("메뉴 수정");

        UpdateButton.setBackground(new java.awt.Color(113, 113, 113));
        UpdateButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("수정");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        MinibarMenu1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarMenu1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinibarMenu1FieldActionPerformed(evt);
            }
        });

        MinibarMenu2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarMenu3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarMenuLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarMenuLabel.setText("메뉴");

        MinibarPriceLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarPriceLabel.setText("가격");

        MinibarMenu4Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarMenu5Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarMenu5Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinibarMenu5FieldActionPerformed(evt);
            }
        });

        MinibarMenu6Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarPrice1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarPrice1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinibarPrice1FieldActionPerformed(evt);
            }
        });

        MinibarPrice2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarPrice3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarPrice4Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarPrice5Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        MinibarPrice6Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RestaurantMenu1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RestaurantMenu2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RestaurantMenu3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RestaurantPrice1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RestaurantPrice1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantPrice1FieldActionPerformed(evt);
            }
        });

        RestaurantPrice2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RestaurantPrice3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServiceMenu1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServiceMenu2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServiceMenu3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServicePrice1Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServicePrice2Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        RoomServicePrice3Field.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomServicePrice3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomServicePrice3FieldActionPerformed(evt);
            }
        });

        RestaurantMenu.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RestaurantMenu.setText("메뉴");

        RestaurantPrice.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RestaurantPrice.setText("가격");

        RoomServiceMenuLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomServiceMenuLabel.setText("메뉴");

        RoomServicePriceLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomServicePriceLabel.setText("가격");

        MinibarLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MinibarLabel.setText("미니바");

        RestaurantLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RestaurantLabel.setText("식당");

        RoomServiceLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        RoomServiceLabel.setText("룸서비스");

        GoBackButton.setBackground(new java.awt.Color(70, 70, 70));
        GoBackButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GoBackButton.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton.setText("뒤로가기");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(MinibarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RoomServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MinibarMenu6Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinibarPrice6Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MinibarMenu5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinibarPrice5Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(RestaurantMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(RestaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(MinibarMenu1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MinibarPrice1Field))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(MinibarMenu2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MinibarPrice2Field))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(MinibarMenu3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(MinibarPrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RestaurantMenu3Field, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                    .addComponent(RestaurantMenu2Field)
                                                    .addComponent(RestaurantMenu1Field, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RestaurantPrice1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RestaurantPrice2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RestaurantPrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RestaurantPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RoomServiceMenu1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(RoomServiceMenu2Field)
                                            .addComponent(RoomServiceMenu3Field)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(RoomServiceMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MinibarMenu4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MinibarPrice4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(MinibarMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(MinibarPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(192, 192, 192)
                                        .addComponent(UpdateButton)
                                        .addGap(91, 91, 91)
                                        .addComponent(GoBackButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoomServicePrice2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoomServicePrice1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoomServicePrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RoomServicePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarLabel)
                    .addComponent(RestaurantLabel)
                    .addComponent(RoomServiceLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenuLabel)
                    .addComponent(MinibarPriceLabel)
                    .addComponent(RestaurantMenu)
                    .addComponent(RestaurantPrice)
                    .addComponent(RoomServiceMenuLabel)
                    .addComponent(RoomServicePriceLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantMenu1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServiceMenu1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantPrice1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServicePrice1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantPrice2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantMenu2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServiceMenu2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServicePrice2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantPrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServicePrice3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantMenu3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomServiceMenu3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu5Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice5Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinibarMenu6Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinibarPrice6Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(GoBackButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        
        
         // 미니바 수정
        if(Emp(MinibarMenu1Field.getText(), MinibarPrice1Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);     
        else if(Emp(MinibarMenu2Field.getText(), MinibarPrice2Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(MinibarMenu3Field.getText(), MinibarPrice3Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(MinibarMenu4Field.getText(), MinibarPrice4Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(MinibarMenu5Field.getText(), MinibarPrice5Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);        
        else if(Emp(MinibarMenu6Field.getText(), MinibarPrice6Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        // 레스토랑 수정
        else if(Emp(RestaurantMenu1Field.getText(), RestaurantPrice1Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(RestaurantMenu2Field.getText(), RestaurantPrice2Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(RestaurantMenu3Field.getText(), RestaurantPrice3Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        // 룸서비스 수정
        else if(Emp(RoomServiceMenu1Field.getText(), RoomServicePrice1Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(RoomServiceMenu2Field.getText(), RoomServicePrice2Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        else if(Emp(RoomServiceMenu3Field.getText(), RoomServicePrice3Field.getText())) JOptionPane.showMessageDialog(this, "메뉴와 가격을 같이 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);       
        else
        {
                UpdateString( "hmsfood", "food_1", "foodtype", "1", MinibarMenu1Field.getText());
            if(MinibarPrice1Field.getText().isEmpty()) UpdateString( "hmsfood", "food_1_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_1_pay", "foodtype", "1", MinibarPrice1Field.getText());
            UpdateString( "hmsfood", "food_2", "foodtype", "1", MinibarMenu2Field.getText());
            if(MinibarPrice2Field.getText().isEmpty()) UpdateString( "hmsfood", "food_2_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_2_pay", "foodtype", "1", MinibarPrice2Field.getText());
            
            
            
            UpdateString( "hmsfood", "food_3", "foodtype", "1", MinibarMenu3Field.getText());
            if(MinibarPrice3Field.getText().isEmpty()) UpdateString( "hmsfood", "food_3_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_3_pay", "foodtype", "1", MinibarPrice3Field.getText());
            UpdateString( "hmsfood", "food_4", "foodtype", "1", MinibarMenu4Field.getText());
            if(MinibarPrice4Field.getText().isEmpty()) UpdateString( "hmsfood", "food_4_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_4_pay", "foodtype", "1", MinibarPrice4Field.getText());
            UpdateString( "hmsfood", "food_5", "foodtype", "1", MinibarMenu5Field.getText());
            if(MinibarPrice5Field.getText().isEmpty()) UpdateString( "hmsfood", "food_5_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_5_pay", "foodtype", "1", MinibarPrice5Field.getText());
            UpdateString( "hmsfood", "food_6", "foodtype", "1", MinibarMenu6Field.getText());
            if(MinibarPrice6Field.getText().isEmpty()) UpdateString( "hmsfood", "food_6_pay", "foodtype", "1", "0");
            else UpdateString( "hmsfood", "food_6_pay", "foodtype", "1", MinibarPrice6Field.getText());
            UpdateString( "hmsfood", "food_1", "foodtype", "2", RestaurantMenu1Field.getText());
            if(RestaurantPrice1Field.getText().isEmpty()) UpdateString( "hmsfood", "food_1_pay", "foodtype", "2", "0");
            else UpdateString( "hmsfood", "food_1_pay", "foodtype", "2", RestaurantPrice1Field.getText());
            UpdateString( "hmsfood", "food_2", "foodtype", "2", RestaurantMenu2Field.getText());
            if(RestaurantPrice2Field.getText().isEmpty()) UpdateString( "hmsfood", "food_2_pay", "foodtype", "2", "0");
            else UpdateString( "hmsfood", "food_2_pay", "foodtype", "2", RestaurantPrice2Field.getText());
            UpdateString( "hmsfood", "food_3", "foodtype", "2", RestaurantMenu3Field.getText());
            if(RestaurantPrice3Field.getText().isEmpty()) UpdateString( "hmsfood", "food_3_pay", "foodtype", "2", "0");
            else UpdateString( "hmsfood", "food_3_pay", "foodtype", "2", RestaurantPrice3Field.getText());
            UpdateString( "hmsfood", "food_1", "foodtype", "3", RoomServiceMenu1Field.getText());
            if(RoomServicePrice1Field.getText().isEmpty()) UpdateString( "hmsfood", "food_1_pay", "foodtype", "3", "0");
            else UpdateString( "hmsfood", "food_1_pay", "foodtype", "3", RoomServicePrice1Field.getText());
            UpdateString( "hmsfood", "food_2", "foodtype", "3", RoomServiceMenu2Field.getText());
            if(RoomServicePrice2Field.getText().isEmpty()) UpdateString( "hmsfood", "food_2_pay", "foodtype", "3", "0");
            else UpdateString( "hmsfood", "food_2_pay", "foodtype", "3", RoomServicePrice2Field.getText());
            UpdateString( "hmsfood", "food_3", "foodtype", "3", RoomServiceMenu3Field.getText());
            if(RoomServicePrice3Field.getText().isEmpty()) UpdateString( "hmsfood", "food_3_pay", "foodtype", "3", "0");
            else UpdateString( "hmsfood", "food_3_pay", "foodtype", "3", RoomServicePrice3Field.getText());
            JOptionPane.showMessageDialog(this, "메뉴가 수정되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                }
        
        dbClose();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void MinibarMenu5FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinibarMenu5FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinibarMenu5FieldActionPerformed

    private void RoomServicePrice3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomServicePrice3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomServicePrice3FieldActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new hmsGUI().setVisible(true);
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void RestaurantPrice1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantPrice1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantPrice1FieldActionPerformed

    private void MinibarMenu1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinibarMenu1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinibarMenu1FieldActionPerformed

    private void MinibarPrice1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinibarPrice1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinibarPrice1FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel MinibarLabel;
    private javax.swing.JTextField MinibarMenu1Field;
    private javax.swing.JTextField MinibarMenu2Field;
    private javax.swing.JTextField MinibarMenu3Field;
    private javax.swing.JTextField MinibarMenu4Field;
    private javax.swing.JTextField MinibarMenu5Field;
    private javax.swing.JTextField MinibarMenu6Field;
    private javax.swing.JLabel MinibarMenuLabel;
    private javax.swing.JTextField MinibarPrice1Field;
    private javax.swing.JTextField MinibarPrice2Field;
    private javax.swing.JTextField MinibarPrice3Field;
    private javax.swing.JTextField MinibarPrice4Field;
    private javax.swing.JTextField MinibarPrice5Field;
    private javax.swing.JTextField MinibarPrice6Field;
    private javax.swing.JLabel MinibarPriceLabel;
    private javax.swing.JLabel RestaurantLabel;
    private javax.swing.JLabel RestaurantMenu;
    private javax.swing.JTextField RestaurantMenu1Field;
    private javax.swing.JTextField RestaurantMenu2Field;
    private javax.swing.JTextField RestaurantMenu3Field;
    private javax.swing.JLabel RestaurantPrice;
    private javax.swing.JTextField RestaurantPrice1Field;
    private javax.swing.JTextField RestaurantPrice2Field;
    private javax.swing.JTextField RestaurantPrice3Field;
    private javax.swing.JLabel RoomServiceLabel;
    private javax.swing.JTextField RoomServiceMenu1Field;
    private javax.swing.JTextField RoomServiceMenu2Field;
    private javax.swing.JTextField RoomServiceMenu3Field;
    private javax.swing.JLabel RoomServiceMenuLabel;
    private javax.swing.JTextField RoomServicePrice1Field;
    private javax.swing.JTextField RoomServicePrice2Field;
    private javax.swing.JTextField RoomServicePrice3Field;
    private javax.swing.JLabel RoomServicePriceLabel;
    private javax.swing.JButton UpdateButton;
    // End of variables declaration//GEN-END:variables
}
