/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_Reservation;

import hms_ETC.Bill;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 송진영
 */
public class hmsCheckout extends hmsDB_Reservation {

    /**
     * Creates new form hmsCheckout
     */
    public void show_room(String v) {
        Checkiin check = roomnumber();
        String row;
        row = check.getroom_num();
        RoomComboBox.addItem(row);
        
    }

    public void show_room() {
        ArrayList<Checkiin> check = roomnum();
        String row;
        for (int i = 0; i < check.size(); i++) {
            row = check.get(i).getroom_num();
            RoomComboBox.addItem(row);
        }

        
        
    }
    
    public hmsCheckout() {
        initComponents();
        dbLoad();
        show_room();
    //  String gd[] = {"gd", "gdd", "gggg", "dsfasdf"};
    //    jComboBox1 = new JComboBox();
    //jComboBox1 = new JComboBox(ss.roomnum().toArray());

       dbClose();
    //jComboBox1.addItem(ss.roomnum().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomLabel = new javax.swing.JLabel();
        COButton = new javax.swing.JButton();
        RoomComboBox = new javax.swing.JComboBox<>();
        GoBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("체크아웃");

        RoomLabel.setText("방번호");

        COButton.setBackground(new java.awt.Color(113, 113, 113));
        COButton.setForeground(new java.awt.Color(255, 255, 255));
        COButton.setText("체크아웃");
        COButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COButtonActionPerformed(evt);
            }
        });

        RoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomComboBoxActionPerformed(evt);
            }
        });

        GoBackButton.setBackground(new java.awt.Color(70, 70, 70));
        GoBackButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GoBackButton.setForeground(new java.awt.Color(255, 255, 255));
        GoBackButton.setText("뒤로가기");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(RoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(COButton)
                .addGap(18, 18, 18)
                .addComponent(GoBackButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomLabel)
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COButton)
                    .addComponent(GoBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void COButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COButtonActionPerformed
        // TODO add your handling code here:
        dbLoad();
        String room_num = RoomComboBox.getSelectedItem().toString();
        
        int q = RoomComboBox.getSelectedIndex();
        
        Calendar cal = Calendar.getInstance();
        Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("YYYYMMdd");
        SimpleDateFormat ft2 = new SimpleDateFormat("dd");
        String theDate = ft.format(date);
        int addPrice = getfoodint("roomcost", "room_num", room_num, "change_rate");
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        int min = cal.get(Calendar.MINUTE);
        int sec = cal.get(Calendar.SECOND);
        String SH = null;
        if(hour < 10) SH = "0"+Integer.toString(hour);
        else SH = Integer.toString(hour);
        String SM = null;
        if(min <10) SM = "0" + Integer.toString(min);
        else SM = Integer.toString(min);
        String SS = null;
        if(sec <10) SS = "0"+Integer.toString(sec);
        else SS = Integer.toString(sec);
        String rCOtime = SH + SM + SS;
        int gCOdate = Integer.parseInt(getDate(room_num));
        int rCOdate = Integer.parseInt(theDate);
        String gCOtime = "110000"; 
        if(gCOdate > rCOdate)
        { 
            dispose();
            new Bill(RoomComboBox.getSelectedItem().toString(),1).setVisible(true);
        }
        else if(gCOdate == rCOdate)
        {
            if(Integer.parseInt(gCOtime) >= Integer.parseInt(rCOtime))
            {
                dispose();
                new Bill(RoomComboBox.getSelectedItem().toString(),1).setVisible(true);
            }
            else 
            {
                Updateint("reservation", "totalPrice", "room_num", room_num, addPrice);
                JOptionPane.showMessageDialog(this, "체크아웃 시간이 오버되어 "+addPrice+"원이 추가되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                new Bill(RoomComboBox.getSelectedItem().toString(),1).setVisible(true);
            }
            
        }
        else
        {
            Updateint("reservation", "totalPrice", "room_num", room_num, addPrice);
            JOptionPane.showMessageDialog(this, "체크아웃 시간이 오버되어 "+addPrice+"원이 초과되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new Bill(RoomComboBox.getSelectedItem().toString(),1).setVisible(true);
        }
        int bar = minibar(room_num);
        int res = restaurant(room_num);
        int roo = roomservice(room_num);
        foodInsert(room_num ,bar,res, roo);
        
        
        RoomComboBox.removeItemAt(q);
        dbClose();
    }//GEN-LAST:event_COButtonActionPerformed

    private void RoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomComboBoxActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new hotelGUI().setVisible(true);
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hmsCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hmsCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hmsCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hmsCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hmsCheckout().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COButton;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JComboBox<String> RoomComboBox;
    private javax.swing.JLabel RoomLabel;
    // End of variables declaration//GEN-END:variables
}
