/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_Reservation;


import javax.swing.JOptionPane;

/**
 *
 * @author yangchang-yun
 */
public class hmsCheckinT extends hmsDB_Booking {

    /**
     * Creates new form hmsCheckin
     */
    public hmsCheckinT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReserNumLabel = new javax.swing.JLabel();
        ReserNumField = new javax.swing.JTextField();
        CIButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("체크인");

        ReserNumLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ReserNumLabel.setText("예약번호를 입력해주세요");

        ReserNumField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ReserNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserNumFieldActionPerformed(evt);
            }
        });

        CIButton.setBackground(new java.awt.Color(113, 113, 113));
        CIButton.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        CIButton.setForeground(new java.awt.Color(255, 255, 255));
        CIButton.setText("체크인");
        CIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(113, 113, 113));
        jButton1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("뒤로가기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ReserNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReserNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CIButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReserNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserNumLabel)
                    .addComponent(CIButton)
                    .addComponent(jButton1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReserNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserNumFieldActionPerformed

    private void CIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIButtonActionPerformed
        // TODO add your handling code here:
        String reserNUM = ReserNumField.getText();
        dbLoad();
        int room_num = get_reserroom(reserNUM);
        boolean Search = searchNUM(reserNUM);
        if (reserNUM.isEmpty()) { //예약번호 입력하지 않은 경우
            JOptionPane.showMessageDialog(this, "예약 번호를 입력해주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        } else if (Search) { //입력한 예약 번호가 있는 경우
            if (CIisPay(reserNUM)) {
                if (searchCHECK(reserNUM) == 0) {
                    RealCI(reserNUM);
                    foodroomInsert(room_num);
                    JOptionPane.showMessageDialog(this, "체크인 완료.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new hotelGUI().setVisible(true);
                } else {
                JOptionPane.showMessageDialog(this, "이미 체크인 된 예약번호입니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "보증이 되지않은 객실임으로 체크인 할 수 없습니다. 보증을 진행해 주세요.", "메세지", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                new Guarantee(reserNUM).setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "일치하는 예약 번호가 없습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
        }
        dbClose();
    }//GEN-LAST:event_CIButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new hotelGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hmsCheckinT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hmsCheckinT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hmsCheckinT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hmsCheckinT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hmsCheckinT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CIButton;
    private javax.swing.JTextField ReserNumField;
    private javax.swing.JLabel ReserNumLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
