/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms_ETC;

import javax.swing.JOptionPane;
import hms_Reservation.hotelGUI;
import hms_FoodSystem.foodtrace;
import hms_FoodSystem.foodService;

/**
 *
 * @author 송진영
 */
public class BillCard extends hmsDB_ETC {

    /**
     * Creates new form BillCard
     */
    String room_num;
    int type;
    String card_num;
    public BillCard(String a, String b, int c) {
           initComponents();
           room_num = b;
           type = c;
           card_num = a;
        if(card_num.isEmpty()){
        CardnumField.setText(null);
        }else{    
        CardnumField.setText(card_num);
        }
     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardnumField = new javax.swing.JTextField();
        PayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("카드결제");

        PayButton.setText("결제");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardnumField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(PayButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayButton)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here: // 결제하면 미결제 금액 0으로 초기화하고 결제 금액 추가
        dbLoad();
        
        int roomF = getCost_Bill(room_num, "roomX");
        int foodF = getCost_Bill(room_num, "foodX");
        int foodtype;
        int coursetype;
        int coursepay = 0;
        if(type > 5) 
        {
            foodtype = 3;
            coursetype = type - 5;
            coursepay = getfoodint("hmsfood", "foodtype", Integer.toString(foodtype), "food_"+coursetype+"_pay");
        }
        else if(type >2 && type <= 5)
        {
            foodtype = 2;
            coursetype = type - 2;
            coursepay = getfoodint("hmsfood", "foodtype", Integer.toString(foodtype), "food_"+coursetype+"_pay");
        }
        
        else if(type == 0)
        {
            int room_cost = get_roomcost(room_num);
            JOptionPane.showMessageDialog(this, room_cost+"원이 결제되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new hotelGUI().setVisible(true);
        }
                
        else if(type == 1 || type == -1)
        {
            JOptionPane.showMessageDialog(this, foodF+roomF+"원이 결제되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE); 
            Updateint("foodsystem", "payment", "room_num",room_num , foodF);
            Updatechange("foodsystem", "food_total_pay", "room_num",room_num , 0);
            Updateint("reservation", "payment", "room_num",room_num , roomF);
            dispose();
            if(type == 1)
            new Bill(room_num,1).setVisible(true);
            else if(type == -1) new Bill(room_num,0).setVisible(true);
        }
        else if(type == 2)
        {
            for(int i=1; i<=6; i++)
          {
            Updatechange("foodsystem", "food_"+i+"_charge", "room_num", room_num, 0);
            Updatechange("foodsystem", "food_service_"+i, "room_num", room_num, 0);
            }
       
            JOptionPane.showMessageDialog(this, foodF+"원이 결제되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE); 
            Updateint("foodsystem", "payment", "room_num",room_num , foodF);
            Updatechange("foodsystem", "food_total_pay", "room_num",room_num , 0);
            dispose();
            new foodtrace().setVisible(true);
        }
        else if(type >= 3)
        {
            JOptionPane.showMessageDialog(this, coursepay+"원이 결제되었습니다.", "메세지", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new foodService().setVisible(true);
        }
        dbClose();
        
        
        
    }//GEN-LAST:event_PayButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardnumField;
    private javax.swing.JButton PayButton;
    // End of variables declaration//GEN-END:variables
}
